[tool.poetry]
name = "lmanage"
version = "0.2.6.02"
description = "LManage is a collection of useful tools for Looker admins to help curate and cleanup content and it's associated source LookML."
keywords = ["keyword", "another_keyword"]
authors = ["hselbie <hselbie@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/looker-open-source/lmanage"
repository = "https://github.com/looker-open-source/lmanage"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.9"
click = "^7.1.2"
icecream = "^2.1.0"
pandas = "^1.2.2"
ipython = "^7.20.0"
tabulate = "^0.8.8"
coloredlogs = "^15.0"
verboselogs = "^1.7"
coloredlogger = "^1.3.12"
pytest-mock = "^3.5.1"
sqlparse = "^0.4.1"
snoop = "^0.3.0"
lookml = "^3.0.3"
debugpy = "^1.3.0"
pynvim = "^0.4.3"
pylint = "^2.9.5"
lkml = "^1.1.1"
flake8 = "^4.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autopep8 = "^1.5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
lmanage = 'lmanage.cli:lmanage'
