[tool.poetry]
name = "lmanage"
version = "0.1.4"
description = ""
authors = ["hselbie <hselbie@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.9"
click = "^7.1.2"
icecream = "^2.1.0"
pandas = "^1.2.2"
ipython = "^7.20.0"
tabulate = "^0.8.8"
coloredlogs = "^15.0"
verboselogs = "^1.7"
coloredlogger = "^1.3.12"
looker-deployer = "^0.3.0"
pytest-mock = "^3.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autopep8 = "^1.5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
lmanage = 'lmanage.cli:lmanage'
